### ISSUE TITLE
'ModelSerializer' has no attribute '_field_mapping' in Django REST framework 3.1.0

### ISSUE THREAD

**Issue by pokidovea** [sunscrapers/djoser#21]
Django REST framework 3.1.0

```
Traceback (most recent call last):
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/djoser/utils.py", line 42, in post
    serializer = self.get_serializer(data=request.DATA)
  File "/home/pokidovea/.virtualenvs/myapp/local/lib/python2.7/site-packages/rest_framework/generics.py", line 109, in get_serializer
    return serializer_class(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/djoser/serializers.py", line 94, in __init__
    self.fields[User.USERNAME_FIELD] = create_username_field()
  File "build/bdist.linux-x86_64/egg/djoser/serializers.py", line 16, in create_username_field
    mapping_dict = serializers.ModelSerializer._field_mapping.mapping
AttributeError: type object 'ModelSerializer' has no attribute '_field_mapping'
```

**Comment by Zeioth** [comment]
Same issue here. Running:
Django rest framework 3.1.0
Django 1.7
Python 3.4.0

**Comment by haxoza** [comment]
Thanks! Pull request looks good. It looks like that API of ModelSerializer changed again and we haven't tested it yet with 3.1 version.

**Comment by haxoza** [comment]
Pull request merged and it all works perfectly!
