### ISSUE TITLE
Error on Registration when 'SEND_ACTIVATION_EMAIL' is True

### ISSUE THREAD

**Issue by edwinharly** [sunscrapers/djoser#293]
I got this error everytime a registration is made, here is my settings.py and the error log. Do I need to setup something before I could use this feature ?
```
DJOSER = {
    'SEND_ACTIVATION_EMAIL': True,
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
}
```
```
Internal Server Error: /auth/users/create/
Traceback (most recent call last):
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\rest_framework\generics.py", line 192, in post
    return self.create(request, *args, **kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\rest_framework\mixins.py", line 21, in create
    self.perform_create(serializer)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\djoser\views.py", line 78, in perform_create
    settings.EMAIL.activation(self.request, context).send(to)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\templated_mail\mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\mail\backends\smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "C:\Users\Edwin\.virtualenvs\edacity-django-react-mK_66CsE\lib\site-packages\django\core\mail\backends\smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "C:\Users\Edwin\AppData\Local\Programs\Python\Python36\Lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\Edwin\AppData\Local\Programs\Python\Python36\Lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\Edwin\AppData\Local\Programs\Python\Python36\Lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\Edwin\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Edwin\AppData\Local\Programs\Python\Python36\Lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by dekoza** [comment]
The registration process requires sending confirmation email. Please refer do [Django docs on email configuration](https://docs.djangoproject.com/pl/2.1/topics/email/).
