### ISSUE TITLE
ModuleNotFoundError: No module named 'social_django'

### ISSUE THREAD

**Issue by shvms** [sunscrapers/djoser#474]
Followed the [Sample Usage](https://djoser.readthedocs.io/en/latest/sample_usage.html) guide and this error came up while migrating the database.
Error Log:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\shvms\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked      
ModuleNotFoundError: No module named 'social_django'
```

**Comment by gebolisasi** [comment]
Try to add social-auth-app-django library using pip 

`pip install social-auth-app-django`

or you can found in this [link](https://pypi.org/project/social-auth-app-django/)

**Comment by sprajosh** [comment]
@shvms Can you confirm if this worked? Do you still have an issue?

**Comment by shvms** [comment]
@sprajosh yep
