### ISSUE TITLE
TypeError: cannot pickle '_io.BufferedReader' object

### ISSUE THREAD

**Issue by Xednom** [sunscrapers/djoser#609]
I've encountered this problem within my web app when doing a password reset. My sending of email to any other features on my web app works except for one of this urls from djoser(yes, even a successful registration email returns this error).

``` 
Internal Server Error: /auth/users/reset_password/
Traceback (most recent call last):
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/djoser/views.py", line 241, in reset_password
    settings.EMAIL.password_reset(self.request, context).send(to)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/templated_mail/mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/mailer/backend.py", line 15, in send_messages
    messages = Message.objects.bulk_create([
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/mailer/backend.py", line 16, in <listcomp>
    Message(email=email) for email in email_messages
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/django/db/models/base.py", line 498, in __init__
    _setattr(self, prop, kwargs[prop])
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/mailer/models.py", line 150, in _set_email
    self.message_data = email_to_db(val)
  File "/home/monde/.virtualenvs/gpg_dev/lib/python3.9/site-packages/mailer/models.py", line 94, in email_to_db
    return base64_encode(pickle.dumps(email)).decode('ascii')
TypeError: cannot pickle '_io.BufferedReader' object
```

**Comment by gradox2020** [comment]
I have the same problem. I use django-mailer==2.2 to send mail

**Comment by Xednom** [comment]
@gradox2020 sorry for the late reply, I was able to fix this by changing my djoser and django-mailer to 2.1(for both).

**Comment by albjoaov** [comment]
Hello @Xednom! Are you just using these two versions and everything is working? Because I am using them and I am getting this error

**Comment by albjoaov** [comment]
Created an question on SO: https://stackoverflow.com/questions/74780034/typeerror-cannot-pickle-io-bufferedreader-object-when-sending-e-mail-with-dj

**Comment by Xednom** [comment]
@albjoaov hello, yes I use both versions - djoser = "^2.1.0" and django-mailer = "^2.1"
