### ISSUE TITLE
please support django 4.0

### ISSUE THREAD

**Issue by find456789** [sunscrapers/djoser#637]
https://docs.djangoproject.com/en/4.0/releases/4.0/

**Comment by chusek9** [comment]
I'm using Djoser with Django 4.0.

At first, when I installed Djoser there was an error about importing force_text.

When I "pip install djoser"
due to dependency pip install older version of social-auth-app-django 4.0.0

so I tried uninstalling social social-auth-app-django and install it again to get social-auth-app-django  version 5.0.0

There is a warning that djoser requires social-auth-app-django below version 5.0.0

I just ignore it.
Everything seems to be working fine.

**Comment by GliderGeek** [comment]
`django-templated-mail` is one of the dependencies of `djoser` and currently lists django 2.1 as the latest supported edition (https://django-templated-mail.readthedocs.io/en/latest/getting_started.html#supported-django-versions). Should that dependency also be upgraded?

I'm asking because additionally we use `django-templated-mail` as a direct dependency.

**Comment by JOY-SAM** [comment]
In Django 4.0.4 While the adding Djoser to the urls I got this error which cant be fixed 
```
urlpatterns = [
     path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/', include('djoser.social.urls')),
]
```
I think it cant be fixed.. Because of version problems..



`Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/joy/Dev/Projects/College-Ecommerce/backend/backend/urls.py", line 31, in <module>
    path('auth/', include('djoser.urls')),
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/djoser/urls/__init__.py", line 1, in <module>
    from .base import urlpatterns
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/djoser/urls/base.py", line 4, in <module>
    from djoser import views
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/djoser/views.py", line 44, in <module>
    class UserViewSet(viewsets.ModelViewSet):
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/djoser/views.py", line 45, in UserViewSet
    serializer_class = settings.SERIALIZERS.user
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/djoser/conf.py", line 19, in __getattribute__
    val = import_string(val)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/Users/joy/Dev/Projects/College-Ecommerce/vEnv/lib/python3.8/site-packages/django/utils/module_loading.py", line 15, in cached_import
    import_module(module_path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'accounts'`

**Comment by coding-Alice** [comment]
Is there any update for this?? I am also facing the "ImportError: cannot import name 'force_text' from 'django.utils.encoding', in offline environment I just simply replaced the force_text to force_str, but I'm currently working in docker environment, wondering how I can fix this issue on my docker.

**Comment by snnbotchway** [comment]
I don't know if this is the best solution, but what I did was pip uninstall
djoser, clone the djoser repository and move it into my project just like
another django app. The latest code fixes most issues but is not an
official release(So keep that in mind). I have comprehensive tests for my
project so this wasn't an issue as the tests passed after this change. Also
had to pip install django-templated-mail.

If you don't want to do this, you have to downgrade to django 3 or do some
sketchy renames of those functions which I'm not a fan of.

Another option is to use something other than djoser.

**Comment by coding-Alice** [comment]
@snnbotchway Thank you for the comment! I solved it with @chusek9 's solution. I realized we're using Pipfile inside our dokcer environment, so I installed social-auth-app-django version 5.0.0 using pipenv, and it works perfectly fine! 😄 

![image](https://user-images.githubusercontent.com/30956835/221934461-e590ccc9-0f1f-4886-b08c-1bb4dedec1f7.png)

**Comment by snnbotchway** [comment]
That's great!
