### ISSUE TITLE
sending backend email on same server : (550, b'No Such User Here')

### ISSUE THREAD

**Issue by coda7777** [sunscrapers/djoser#754]
So i'm working with Djoser and it send the SMTP emails correctly when registering, activation, reseting password etc. 
however that works when i test it on gmail or hotmail... etc

I'm on dev local server, and i have bunch of accounts on my app created via backend or create superuser or even registered via app and activated manually from admin. these accounts are on my hosted server and i keep getting these errors that `no such user` even though i have 2 of these accounts open on mail box and working absolutely fine 
```
Trace : 
  File "D:\Vue\HotelFacts-backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "..path..\venv\lib\site-packages\djoser\views.py", line 224, in set_password
    settings.EMAIL.password_changed_confirmation(self.request, context).send(to)
  File "..path..\venv\lib\site-packages\templated_mail\mail.py", line 78, in send
    super(BaseEmailMessage, self).send(*args, **kwargs)
  File "..path..\venv\lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "..path..\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 131, in send_messages
    sent = self._send(message)
  File "..path..\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 149, in _send
    self.connection.sendmail(
  File "..path..\AppData\Local\Programs\Python\Python39\lib\smtplib.py", line 905, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'mr@royalsafari.net': (550, b'No Such User Here')}
```

example emails :
`operation1@hotelfacts.net | mr@royalsafari.net | admin@ananastours.com`

Hyporthetically it should be fine for users but propaply not all and it also casue a failure in functions such as Change Password because it return with : 

```
Uncaught (in promise) Error: Request failed with status code 403
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
```

**Comment by tomwojcik** [comment]
Unrelated to Djoser. No Such User Here is the response from your SMTP server.
