### ISSUE TITLE
error on test projetc

### ISSUE THREAD

**Issue by HishamArshad** [sunscrapers/djoser#762]
The error ocurs when i run migrations, migrate and runserver:
here is this please fix
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\arsha\OneDrive\Desktop\test\djoser\djoser\webauthn\urls.py", line 3, in <module>
    from . import views
  File "C:\Users\arsha\OneDrive\Desktop\test\djoser\djoser\webauthn\views.py", line 8, in <module>
    from webauthn import (
ImportError: cannot import name 'WebAuthnAssertionOptions' from 'webauthn' (C:\Users\arsha\OneDrive\Desktop\test\myenv\Lib\site-packages\webauthn\__init__.py)

**Comment by tomwojcik** [comment]
Did you follow https://djoser.readthedocs.io/en/latest/webauthn.html#configuration ? I assume you added `djoser.webauthn` to INSTALLED_APPS but did not install `webauthn`?

**Comment by araggohnxd** [comment]
I'm facing a similar problem, following the steps from **https://djoser.readthedocs.io/en/latest/sample_usage.html**:

<details>
<summary>Output</summary>


```sh
$ ./manage.py migrate
Traceback (most recent call last):
  File "/home/araggohnxd/studies/djoser/testproject/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/araggohnxd/studies/djoser/testproject/urls.py", line 9, in <module>
    re_path(r"^webauthn/", include("djoser.webauthn.urls")),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/djoser/webauthn/urls.py", line 3, in <module>
    from . import views
  File "/home/araggohnxd/studies/djoser/env/lib/python3.12/site-packages/djoser/webauthn/views.py", line 8, in <module>
    from webauthn import (
ModuleNotFoundError: No module named 'webauthn'
```


<details/>
